algorithm: 'RA'
num_nodes: 4
edge_index: [[0,0,0,1,1,3,3], [1,2,3,2,3,0,1]]
pos_test_edges: [[0, 1], [1, 2]]
neg_test_edges: [[0, 1], [2, 0]]
train_scores_target: ['2/2', 0, '1/2', 0, 0, '1/2', 0]
pos_scores_target: ['2/2', 0]
neg_scores_target: [0, '2/2']
iso_test_edges: 'None'