algorithm: 'RA'
num_nodes: 4
edge_index: [[0,0,1,3], [2,3,2,1]]
pos_test_edges: [[0, 0], [2, 3]]
neg_test_edges: [[0, 3], [1, 2]]
train_scores_target: [0, 0, 0, 0]
pos_scores_target: [0, 0]
neg_scores_target: ['1/2', 0]
iso_test_edges: 'None'