algorithm: 'PA'
num_nodes: 5
edge_index: [[2, 2, 3, 3, 4, 0], [1, 4, 1, 4, 0, 1]] # create a graph with 2 isomorphic nodes 2 & 3
pos_test_edges: [[0, 2], [1, 1]]
neg_test_edges: [[2, 3], [0, 0]]
train_scores_target: ['2*0', '2*1', '2*0', '2*1', '1*1', '1*0']
pos_scores_target: ['1*0', '2*0']
neg_scores_target: ['2*1', '2*1']
iso_test_edges: [[2, 3], [0, 0]]