device: 0
seed: 1
runs: 1

dataset:
  name: cora
  use_text: False
  val_pct: 0.1
  test_pct: 0.2


  dataloader:
    load_features: False
    load_hashes: False
    cache_subgraph_features: False
    max_hash_hops: 2
    use_RA: False
    hll_p: 8
    sign_k: 0
    num_negs: 1
    subgraph_feature_batch_size: 11000000
    floor_sf: 0
    use_struct_feature: True
    year: 0
    use_zero_one: 0
    use_feature: False
    batch_size: 1024

gnn:
  model:
    name: 'ELPH'
    K: 100
    add_normed_features: False

    config: ''
    max_dist: 4

    max_nodes_per_hop: null
    max_z: 1000
    minhash_num_perm: 128
    node_label: drnl
    num_hops: 1
    num_seal_layers: 3


    opts: []
    preprocessing: null

    propagate_embeddings: False
    ratio_per_hop: 1.0
    rep: 0
    rep_doc: 1

    use_edge_weight: False

    use_text: True
    use_valedges_as_input: False
    use_wandb_offline: False
    hidden_channels: 1024
    sortpool_k: 0.6
    dynamic_train: False
    
  log:
    log_features: False
    log_steps: 1
    loss: bce
    lr: 0.0001

train:
  dropout: 0.5
  dynamic_test: False

  dynamic_val: False
  epochs: 2
  eval_batch_size: 1000000
  eval_metric: hits
  eval_steps: 1
  feature_dropout: 0.5
  feature_prop: gcn

  label_dropout: 0.5
  label_pooling: add
  save_model: False
  save_result: True
  seal_pooling: edge
  sign_dropout: 0.5

  test_samples: .inf
  train_cache_size: .inf
  node_embedding: False
  pretrained_node_embedding: null
  train_samples: .inf
  val_samples: .inf

wandb:
  enable: True
  wandb_entity: graph-diffusion-model-link-prediction
  wandb_epoch_list:
    - 0
    - 1
    - 2
    - 4
    - 8
    - 16
  wandb_group: reconstruct
  wandb_log_freq: 1
  wandb_notes: None
  wandb_output_dir: ./wandb_output
  wandb_project: link-prediction
  wandb_run_name: null
  wandb_sweep: False
  wandb_tags: baseline
  wandb_track_grad_flow: False
  wandb_watch_grad: False
  weight_decay: 0
  use_wandb_offline: False

device:
  num_workers: 11